<?php

namespace PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SendEmailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendEmailsRepository extends EntityRepository
{
}
